In [1]:
import numpy as np

last_rows = np.random.randn(1, 1)
print(last_rows)

[[0.12162053]]


In [37]:
last_rows[-1,:]

array([0.40959322])

In [2]:
np.random.randn(5,1).cumsum(axis=0)

array([[ 1.85857427],
       [ 2.1449622 ],
       [ 1.57074129],
       [ 1.96104406],
       [-0.72319877]])

In [3]:
new_rows = last_rows[-1,:] + np.random.randn(5,1).cumsum(axis=0)
print(new_rows)

[[ 1.17462134]
 [-1.12657956]
 [ 0.50826781]
 [ 2.01716967]
 [ 3.92287464]]


In [4]:
new_rows

array([[ 1.17462134],
       [-1.12657956],
       [ 0.50826781],
       [ 2.01716967],
       [ 3.92287464]])