In [38]:
import numpy as np

last_rows = np.random.randn(1, 1)
print(last_rows)

[[-0.39486516]]


In [37]:
last_rows[-1,:]

array([0.40959322])

In [40]:
np.random.randn(5,1).cumsum(axis=0)

array([[-0.10310123],
       [ 0.20814286],
       [-0.59354828],
       [-0.34566919],
       [-0.48895503]])

In [43]:
new_rows = last_rows[-1,:] + np.random.randn(5,1).cumsum(axis=0)
print(new_rows)

[[0.02525892]
 [1.08260837]
 [0.95669555]
 [2.21609252]
 [2.37973768]]
